# Generated by Django 5.0.3 on 2024-04-21 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='contact_number',
            new_name='contact_no',
        ),
    ]
